---
title: "Trabajo de Puntos Extra"
author: "NayelyA.C10561_KhiaraM.C25244"
format:
  dashboard:
    orientation: rows
   
---
```{r}
#| label: carga_paquetes
#| message: false
#| warning: false

library(tidyverse)
library(plotly)
library(DT)
library(leaflet)
library(sf)
library(ggthemes)
library(hrbrthemes)
library(viridisLite)
```

```{r}
#| label: carga-datos

especies_reptiles <-
  st_read("especies-reptiles.csv", 
             quiet = TRUE)


registros_reptiles <-
  st_read("registros-reptiles.csv", 
             quiet = TRUE, 
             options = c(
      "X_POSSIBLE_NAMES=decimalLongitude", 
      "Y_POSSIBLE_NAMES=decimalLatitude"))

st_crs(registros_reptiles) <- 4326

regiones_socioeconomicas <- 
  st_read("regiones-socioeconomicas.gpkg", quiet = TRUE)
```

```{r}
#| label: filtros

filtro_Squamata <- 
  registros_reptiles |>
  filter(class == "Squamata")

filtro_menor <-
  especies_reptiles|>
  filter(iucnRedListCategory == "LC")
```


```{r}
#| label: Uniones_datos

registros_union_especies <- 
  left_join(
    x = filtro_Squamata,
    y = filtro_menor,
    by = "species")

registros_union_especies_regiones <-
  st_join(
    x = registros_union_especies,
    y = dplyr::select(regiones_socioeconomicas, region),
    join = st_within
  )
```

```{r}
#| label: conteo

riqueza_x_regiones <- 
  registros_union_especies_regiones |> 
  st_drop_geometry() |>
  group_by(region) |>
  summarize(conteo = n_distinct(species, na.rm = TRUE))
```

```{r}
#| label: union_no_espacial

regiones_union_riqueza <- 
  left_join(
    x = regiones_socioeconomicas, 
    y = riqueza_x_regiones,
    by = "region"
  ) |>
  replace_na(list(riqueza_region_iguanidae = 0))
```

# Mapa coropletas

## Row

```{r}
#| label: mapa
#| title: "Mapa de riqueza de especies de preocupación menor de la clase Squamata."

colores_riqueza_especies <-
  colorNumeric(
    palette = "Reds", 
    domain = regiones_union_riqueza$conteo, 
    na.color = "transparent"
  ) 

colores_especies <- colorFactor(
  palette = viridis(length(unique(registros_union_especies_regiones$species))),
  domain = registros_union_especies_regiones$species
)

  leaflet() |>
  setView(
    lng = -84.194552,
    lat = 9.572735,
    zoom = 7) |>
  addTiles(group = "Mapa general (OpenStreetMap") |>
  addProviderTiles(
    providers$Esri.WorldImagery,
    group = "Imágenes satelitales (ESRI World Imagery)"
  ) |>
    addPolygons(
    data = regiones_union_riqueza,
    fillColor = ~ colores_riqueza_especies(regiones_union_riqueza$conteo),
    fillOpacity = "black",
    stroke = TRUE,
    weight = 1.0,
    popup = paste(
      paste("<strong>Region:</strong>", regiones_union_riqueza$region),
      paste("<strong>Riqueza de especies:</strong>", regiones_union_riqueza$conteo),
      sep = "<br/>"
    ),
    group = "Riqueza de especies"
  ) |>
    addScaleBar(
      position = "bottomleft",
      options = scaleBarOptions(imperial = FALSE)
    ) |>
    addLegend(
    position = "bottomleft",
    pal = colores_riqueza_especies,
    values = regiones_union_riqueza$conteo,
    group = "Riqueza de especies",
    title = "Riquezas de especies"
  ) |>
  addLayersControl(
    baseGroups = c(
      "Mapa general (OSM)",
      "Imágenes satelitales (ESRI World Imagery)"
    ),
    overlayGroups = c(
      "Riqueza de especies",
      "Regostro de presencia"
    )
  )
```

